/*
 * Copyright COCKTAIL (www.cocktail.org), 1995, 2010 This software
 * is governed by the CeCILL license under French law and abiding by the
 * rules of distribution of free software. You can use, modify and/or
 * redistribute the software under the terms of the CeCILL license as
 * circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info".
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability. In this
 * respect, the user's attention is drawn to the risks associated with loading,
 * using, modifying and/or developing or reproducing the software by the user
 * in light of its specific status of free software, that may mean that it
 * is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security. The
 * fact that you are presently reading this means that you have had knowledge
 * of the CeCILL license and that you accept its terms.
 */
package fr.univlr.cri.planning.components;
// Generated by the WOLips TemplateEngine Plug-in at 18 sept. 2006 14:47:19

import org.cocktail.fwkcktlwebapp.server.components.CktlMenuItemSet;
import org.cocktail.fwkcktlwebapp.server.components.CktlMenuListener;
import org.cocktail.fwkcktlwebapp.server.components.CktlWebPage;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

import fr.univlr.cri.planning.Session;

/**
 * Le menu de la partie administration du serveur
 * 
 * @author Cyril TARADE <cyril.tarade at univ-lr.fr>
 */

public class Menu extends CktlWebPage {

  private Session session = (Session) session();
  
  private final static int ITEM_MENU_VISU							= 1;
  private final static int ITEM_MENU_VISU_METH_SERVER 	= 11;
  private final static int ITEM_MENU_VISU_METH_CLIENT 	= 12;
  private final static int ITEM_MENU_ADMIN							= 2;
  private final static int ITEM_MENU_ADMIN_METH_SERVER	= 21;
  private final static int ITEM_MENU_QUITTER           	= 4;
  
  /** le titre affiche entre le 2 groupes d'onglets */
  public String title;
  
  public Menu(WOContext context) {
    super(context);
  }


  public CktlMenuListener listener() {
  	if (session.getMenuLister() == null)
  		session.setMenuLister(new AdminPlanningMenuListener());
    return session.getMenuLister();
  }
  
  
  public class AdminPlanningMenuListener extends CktlMenuListener {

    // M�thodes de listener
  	public void initMenu() {
    }
  	
    public WOComponent selectMenu(int id) {
      WOComponent resultPage = null;
      switch(id) {
        case ITEM_MENU_VISU_METH_SERVER  :     
        	resultPage = session.getSavedPageWithName(PageMethServeur.class.getName());     
        	title = "Correspondance applications <-> m�thodes serveurs";
        	break;
        case ITEM_MENU_VISU_METH_CLIENT  :     
        	resultPage = session.getSavedPageWithName(PageMethCliente.class.getName());       
        	title = "Correspondance m�thodes clientes <-> applications";
        	break;
        case ITEM_MENU_ADMIN_METH_SERVER :     
        	resultPage = session.getSavedPageWithName(PageAdminMethServeur.class.getName());       
        	title = "Affectation des methodes serveurs aux applications";
        	break;
        case ITEM_MENU_QUITTER           :    
        	resultPage = session.logout();                                     
        	break;
      }
      return resultPage;
    }

    public WOComponent disconnect() {
      return session.logout();
    }
 
  }
  
  public CktlMenuItemSet menuItemSet() {
    if (session.getDtMenuItemSet() == null)
      session.setDtMenuItemSet(createMenu());
    return session.getDtMenuItemSet();
  }
  
  private CktlMenuItemSet createMenu() {
    
    CktlMenuItemSet menuItemSet = new CktlMenuItemSet();
    // Initialisation de menu
    menuItemSet.addMenuItem(ITEM_MENU_VISU, "Informations", "Afficher la configuration du serveur (via ZAP/SAUT)", "_top");
    menuItemSet.addMenuSubItem(ITEM_MENU_VISU, ITEM_MENU_VISU_METH_SERVER, "M&eacute;thodes serveurs", "Applications productrices des donn&eacute;es", "_top");
    menuItemSet.addMenuSubItem(ITEM_MENU_VISU, ITEM_MENU_VISU_METH_CLIENT, "M&eacute;thodes clientes", "Applications consommatrices de donn&eacute;es", "_top");
    menuItemSet.addMenuItem(ITEM_MENU_ADMIN, "Configuration", "", "_top");
    menuItemSet.addMenuSubItem(ITEM_MENU_ADMIN, ITEM_MENU_ADMIN_METH_SERVER, "M&eacute;thodes serveurs", "Affectation des methodes serveurs aux applications", "_top");
    menuItemSet.addMenuItem(ITEM_MENU_QUITTER, "Quitter", "Fermer votre session dans cette application", "_top");

    return menuItemSet;
  }

}